/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-high': '#eae7e7',
        'surface-highest': '#e4e2e1',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#50453b',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#82756a',
        'outline-variant': '#d4c4b7',
        'primary': '#603d16',
        'on-primary': '#ffffff',
        'primary-container': '#7b542b',
        'on-primary-container': '#ffcb9b',
        'inverse-primary': '#f1bd8b',
        'secondary': '#615e56',
        'on-secondary': '#ffffff',
        'secondary-container': '#e8e2d7',
        'on-secondary-container': '#67645c',
        'tertiary': '#5c3f00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7a5500',
        'on-tertiary-container': '#ffcd77',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'gold': '#d9a441',
        'cream': '#f6f0e5',
        'beige': '#efe5d5',
        'dark-text': '#2a2a2a',
        'success': '#3a7d44',
      },
      fontFamily: {
        'serif': ['Libre Caslon Text', 'Georgia', 'serif'],
        'sans': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
