/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        'gaav-earth': '#3B2314',
        'gaav-cream': '#F5EDE0',
        'gaav-bark': '#8B6B4A',
        'gaav-sand': '#E8DDD0',
        'gaav-wheat': '#A0845C',
        'gaav-clay': '#C4B5A2',
        
        'surface': '#F5EDE0',
        'surface-dim': '#E8DDD0',
        'surface-bright': '#FFFFFF',
        'surface-low': '#F5EDE0',
        'surface-container': '#E8DDD0',
        'surface-high': '#C4B5A2',
        'surface-highest': '#A0845C',
        'on-surface': '#1A1A1A',
        'on-surface-variant': '#3B2314',
        'inverse-surface': '#3B2314',
        'inverse-on-surface': '#F5EDE0',
        'outline': '#8B6B4A',
        'outline-variant': '#C4B5A2',
        'primary': '#3B2314',
        'on-primary': '#F5EDE0',
        'primary-container': '#8B6B4A',
        'on-primary-container': '#F5EDE0',
        'inverse-primary': '#A0845C',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'gold': '#d9a441',
        'success': '#3a7d44',
      },
      fontFamily: {
        'serif': ['Playfair Display', 'serif'],
        'sans': ['Anek Devanagari', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
